### ISSUE TITLE
Peer to Peer Coding Review

### ISSUE THREAD

**Issue by annaeliana7** [abenaTenkorang/Todo-list#4]
### @abenaTenkorang 🐶 🐾 🐾 

Your README file looks great, however there is an issue with your live demo. Kindly run build and run start in your command line and push changes into your main branch. Please fix your live demo link to activate deployment. Thank you! 

<img width="221" alt="1  Live Demo Not working" src="https://user-images.githubusercontent.com/112557951/208610616-41c10d02-0993-4c45-bd15-6a47a3bce8a0.png">

**Comment by abenaTenkorang** [comment]
Thank you for drawing my attention. It has been rectified @annaeliana7
